--1--
SELECT C.NOMBRECLIENTE, E.NOMBRE||', '||E.APELLIDO1||' '||E.APELLIDO2 "REPRESENTANTE"
FROM CLIENTES C, EMPLEADOS E
WHERE C.CODIGOEMPLEADOREPVENTAS = E.CODIGOEMPLEADO
ORDER BY CODIGOEMPLEADO;

--2--
SELECT C.NOMBRECLIENTE, P.CANTIDAD
FROM CLIENTES C, PAGOS P
WHERE C.CODIGOCLIENTE = P.CODIGOCLIENTE
AND (P.CANTIDAD = (SELECT MAX(CANTIDAD) FROM PAGOS)
OR P.CANTIDAD = (SELECT MIN(CANTIDAD) FROM PAGOS));

--3--
SELECT P.CODIGOCLIENTE, C.NOMBRECLIENTE, INITCAP(P.ESTADO), COUNT(P.CODIGOPEDIDO) AS PEDIDOS
FROM PEDIDOS P, CLIENTES C
WHERE P.CODIGOCLIENTE = C.CODIGOCLIENTE
GROUP BY P.CODIGOCLIENTE, P.ESTADO , C.NOMBRECLIENTE
ORDER BY P.CODIGOCLIENTE, INITCAP(P.ESTADO);

--4--
SELECT E.CODIGOEMPLEADO, COUNT(C.CODIGOCLIENTE) "NUMERO DE CLIENTES"
FROM EMPLEADOS E, CLIENTES C
WHERE C.CODIGOEMPLEADOREPVENTAS (+) = E.CODIGOEMPLEADO
GROUP BY CODIGOEMPLEADO
ORDER BY CODIGOEMPLEADO;

--5--
SELECT C.NOMBRECLIENTE, E.NOMBRE "EMPLEADO"
FROM EMPLEADOS E, CLIENTES C, PAGOS P
WHERE C.CODIGOEMPLEADOREPVENTAS = E.CODIGOEMPLEADO 
AND P.CANTIDAD = NULL;

--6--
SELECT P.NOMBRE, SUM(D.CANTIDAD), SUM(CANTIDAD * PRECIOUNIDAD) AS "TOTAL SIN IVA", SUM((CANTIDAD * PRECIOUNIDAD * 0.21) + (CANTIDAD * PRECIOUNIDAD)) AS "TOTAL CON IVA"
FROM PRODUCTOS P, DETALLEPEDIDOS D
WHERE D.CODIGOPRODUCTO = P.CODIGOPRODUCTO
GROUP BY P.NOMBRE
HAVING SUM (CANTIDAD * PRECIOUNIDAD) >= 3000;