--1
SELECT CIUDAD, TELEFONOS
FROM OFICINAS
WHERE UPPER(PAIS) = 'EEUU'
ORDER BY CIUDAD;
--2
SELECT CODIGOOFICINA, CIUDAD, REGION, PAIS
FROM OFICINAS
WHERE LOWER(PAIS) LIKE 'E%'
ORDER BY CIUDAD ASC;
--3
SELECT DISTINCT UPPER(ESTADO) 
FROM PEDIDOS;
--4
SELECT COUNT(*) AS *CANTIDAD EMPLEADOS EMPRESA* 
FROM EMPLEADOS;
--5
SELECT COUNT(CODIGOCLIENTE)
FROM CLIENTE
ORDER BY PAIS;
--6
SELECT AVG(CANTIDAD)
FROM PAGOS
--WHERE FECHAPAGO BETWEEN '1-1-2007' AND '31-12-2007';
WHERE EXTRACT(YEAR FROM FECHAPAGO)=2007;
--7
SELECT *
FROM CLIENTES;
--8
--9
--10
--11
--12
