/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import Excepciones.*;
import Modelo.UML.*;
import gabinete.Gabinete;

/**
 *
 * @author Alejandro
 */
public class AltaAbogados extends javax.swing.JFrame {    
    static boolean error,error2,modifi;
    static String CadenaError;   
    static Abogados a;
    /**
     * Creates new form AltaAbogados
     */
    public AltaAbogados() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        
        modifi=false;
        //Errores
        ErrDni.setVisible(false);
        ErrNombre.setVisible(false);
        ErrAp1.setVisible(false);
        ErrAp2.setVisible(false);
        ErrDir.setVisible(false);
    }
    public AltaAbogados(boolean a) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        goenable(true,false);
        modifi=a;
        //Errores
        ErrDni.setVisible(false);
        ErrNombre.setVisible(false);
        ErrAp1.setVisible(false);
        ErrAp2.setVisible(false);
        ErrDir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfAp2 = new javax.swing.JTextField();
        tfAp1 = new javax.swing.JTextField();
        tfDni = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfDir = new javax.swing.JTextField();
        ErrDni = new javax.swing.JLabel();
        ErrNombre = new javax.swing.JLabel();
        ErrAp1 = new javax.swing.JLabel();
        ErrAp2 = new javax.swing.JLabel();
        ErrDir = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bA = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DNI");

        jLabel2.setText("Nombre");

        jLabel3.setText("Primer apellido");

        jLabel4.setText("Segundo apellido");

        jLabel5.setText("Direccion");

        tfDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDniActionPerformed(evt);
            }
        });

        ErrDni.setForeground(new java.awt.Color(255, 51, 51));
        ErrDni.setText("**Requerido**");

        ErrNombre.setForeground(new java.awt.Color(255, 51, 51));
        ErrNombre.setText("**Requerido**");

        ErrAp1.setForeground(new java.awt.Color(255, 51, 51));
        ErrAp1.setText("**Requerido**");

        ErrAp2.setForeground(new java.awt.Color(255, 51, 51));
        ErrAp2.setText("**Requerido**");

        ErrDir.setForeground(new java.awt.Color(255, 51, 51));
        ErrDir.setText("**Requerido**");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Alta de Abogados");

        bA.setText("Aceptar");
        bA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(tfAp1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ErrDni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ErrNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ErrAp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfAp2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ErrAp2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfDir, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ErrDir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(bA)
                .addGap(92, 92, 92)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ErrDni))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ErrNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfAp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ErrAp1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ErrAp2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ErrDir))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bA)
                    .addComponent(jButton2))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAActionPerformed
        // TODO add your handling code here:
        try{
            if(validar()&&!modifi){
                Gabinete.crearAbogado(tfDni.getText(), tfNombre.getText(), tfAp1.getText(), tfAp2.getText(), tfDir.getText());
                JOptionPane.showMessageDialog(this, "Registro insertado correctamente");
                Gabinete.next(this);
            }else if(validar()&&modifi){
                Gabinete.modificarAbogado(tfDni.getText(), tfNombre.getText(), tfAp1.getText(), tfAp2.getText(), tfDir.getText());
                JOptionPane.showMessageDialog(this, "Registro actualizado correctamente");
                Gabinete.volver(this);
            }
        }catch(Exception e){
            System.out.println("Problemas insertando"+e.getCause());
        }
        
    }//GEN-LAST:event_bAActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Gabinete.volver(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDniActionPerformed
        // TODO add your handling code here:
        if(modifi){
            a=Gabinete.find(tfDni.getText());
            if(a==null)
                JOptionPane.showMessageDialog(this, "No se ha encontrado el abogado");
            else{
                mostrar(a);
                goenable(true, true);
            }
        }
    }//GEN-LAST:event_tfDniActionPerformed
    public void goenable(boolean a, boolean b){
        tfDni.setEnabled(a);
        tfNombre.setEnabled(b);
        tfAp1.setEnabled(b);
        tfAp2.setEnabled(b);
        tfDir.setEnabled(b);
        bA.setEnabled(b);
    }
    public boolean validar(){
        boolean ret=true;
        CadenaError="Los siguientes elementos estan en un formato incorrecto\n";
        error2=false;
        try{
            if(!validation(tfDni.getText(),"^.*$",ErrDni))
                ret=false;
            if(error){
                CadenaError+="-DNI\n";
                error2=true;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Ha ocurrido un error");
        } 
        finally{
            try{
                if(!validation(tfNombre.getText(),"^.*$",ErrNombre))
                    ret=false;
                if(error){
                    CadenaError+="-Nombre\n";
                    error2=true;
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Ha ocurrido un error");
            } 
            finally{
                try{
                    if(!validation(tfAp1.getText(),"^.*$",ErrAp1))
                        ret=false;
                    if(error){
                        CadenaError+="-Primer apellido\n";
                        error2=true;
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this,"Ha ocurrido un error");
                } 
                finally{
                    try{
                        if(!validation(tfAp2.getText(),"^.*$",ErrAp2))
                            ret=false;
                        if(error){
                            CadenaError+="-Segundo apellido\n";
                            error2=true;
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(this,"Ha ocurrido un error");        
                    }
                    finally{
                        try{
                        if(!validation(tfDir.getText(),"^.*$",ErrDir))
                            ret=false;
                        if(error){
                            CadenaError+="-Direccion\n";
                            error2=true;
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(this,"Ha ocurrido un error");        
                        }
                        finally{
                            if(error2)
                                JOptionPane.showMessageDialog(this, CadenaError);
                        }
                    }
                }   
            }
        }  
        return ret;
    }
    public boolean validation(String campo,String regex, javax.swing.JLabel err){
        try{
            if(campo.isEmpty())
                throw new DatoVacio();
            else
                err.setVisible(false);
            if(!pattern(campo,regex))
                throw new DatoNoValido();
        }catch (DatoVacio e){            
            err.setVisible(true);
            return false;
        }catch (DatoNoValido e){
            error=true;
            return false;                   
        }
        error=false;
        return true;
    }
    public boolean pattern(String dato, String regex){
        Pattern pat=Pattern.compile(regex);
        Matcher m=pat.matcher(dato);
        return m.matches();
    } 
    public void mostrar(Abogados a){
        tfDni.setText(a.getDni());
        tfNombre.setText(a.getNombre());
        tfAp1.setText(a.getApe1());
        tfAp2.setText(a.getApe2());
        tfDir.setText(a.getDir());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaAbogados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaAbogados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaAbogados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaAbogados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaAbogados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrAp1;
    private javax.swing.JLabel ErrAp2;
    private javax.swing.JLabel ErrDir;
    private javax.swing.JLabel ErrDni;
    private javax.swing.JLabel ErrNombre;
    private javax.swing.JButton bA;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfAp1;
    private javax.swing.JTextField tfAp2;
    private javax.swing.JTextField tfDir;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
