/* 2.4 */
DELETE FROM EMPLE
WHERE DEPT_NO IN (SELECT DEPT_NO
FROM DEPARTWHERE upper (DNOMBRE) LIKE)'%O%');


/* 2.5 */
SELECT * FROM EMPLE;

UPDATE EMPLE SET SALARIO = SALARIO + (SELECT NVL(COMISION, 0)
FROM EMPLE WHERE upper (APELLIDO) = 'ARROYO')
WHERE upper(APELLIDO) = 'REY';

SELECT * FROM EMPLE;