/* COPIADO EN CLASE, NO ESTOY SEGURO DE HABER COPIADO TODO CORRECTAMENTE */

/* Ejercicio 1 */

SELECT APELLIDO empleado, NVL(TO_CHAR(ID_JEFE)), 'NO TIENE JEFE') jefe
FROM EMPLE
ORDER BY ID_JEFE DESC;

/* Ejercicio 2 */

SELECT EMP_NO empleado, SALARIO salario,
        TRUNC (SALARIO/100) as "PORCENTAJE DE MOVILIZACION"
FROM EMPLE;

/* Ejercicio 3*/

SELECT APELLIDO apellido, OFICIO trabajao,
        INITCAP(SUBSTR(APELLIDO,1,3)) || LENGHT(APELLIDO) || OFICIO nombre_usuario,
        TO_CHAR(FECHA_ALTA,'MMYYYY') || UPPER(SUBSTR(APELLIDO,-2)) "CLAVE USUARIO"

/* Ejercicio 4 */

SELECT APELLIDO "NOMBRE EMPLEADO",
        TO_CHAR(SALARIO, '999,999.999')salario,
        TO_CHAR((SALARIO * SUBSTR(SALARIO,1,1)/100),'9,999.999') reajuste
FROM EMPLE;

/* Ejercicio 5 */

SELECT EMP_NO "ID EMPLEADO", SALARIO "SALARIO SIN COMISION"
        NVL(TO_CHAR(COMISION_PCT), 'SIN COMISION') "PORC. COMISION"
        NVL2(COMISION_PCT,SALARIO * COMISION_PCT,0) "VALOR COMISION"
        NVL2(COMISION_PCT,SALARIO + (SALARIO * COMISION_PCT),SALARIO) "SALARIO TOTAL"
FROM EMPLE;

/* Ejercicio 6 */

