--1--
SELECT DISTINCT EMPLE.OFICIO, DEPART.LOC
FROM EMPLE, DEPART
WHERE EMPLE.DEPT_NO = 10
AND EMPLE.DEPT_NO = DEPART.DEPT_NO;

--2--
SELECT DEPART.DEPT_NO, DEPART.DNOMBRE, COUNT(EMPLE.EMP_NO) AS "NUMERO DE EMPLEADOS"
FROM EMPLE, DEPART
WHERE EMPLE.DEPT_NO(+) = 10
GROUP BY DEPART.DEPT_NO, DEPART.DNOMBRE
ORDER BY DEPART.DEPT_NO;

--3--
SELECT EMPLE.DEPT_NO, DNOMBRE, COUNT(*) "NUMERO DE EMPLEADOS"
FROM EMPLE, DEPART
WHERE EMPLE.DEPT_NO = DEPART.DEPT_NO
GROUP BY EMPLE.DEPT_NO, DNOMBRE
HAVING COUNT(*) = (SELECT MAX(COUNT(*))
                  FROM EMPLE
                  GROUP BY DEPT_NO);
                  
--4--
SELECT E.APELLIDO, D.DNOMBRE "NOMBRE DEPARTAMENTO", E.SALARIO
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO
AND (SALARIO, NVL(COMISION_PCT, -1))
    IN (SELECT SALARIO, NVL(COMISION_PCT, -1)
        FROM EMPLE E, DEPART D
        WHERE E.DEPT_NO = D.DEPT_NO
        AND UPPER(LOC) = 'BARCELONA');