--1--
SELECT APELLIDO, OFICIO, EMP_NO, DNOMBRE, LOC 
FROM EMPLE, DEPART
WHERE EMPLE.DEPT_NO=DEPART.DEPT_NO
ORDER BY APELLIDO;

--2--
SELECT EMPLE.*, LOC 
FROM EMPLE, DEPART
WHERE EMPLE.DEPT_NO=DEPART.DEPT_NO --JOIN = UNION DE LAS TABLAS
AND UPPER(LOC)IN('MADRID', 'BARCELONA');

--3--
SELECT E.EMP_NO, E.APELLIDO, J.APELLIDO "APELLIDO JEFE"
FROM EMPLE E, EMPLE J
WHERE E.EMP_NO=J.ID_JEFE
ORDER BY E.APELLIDO;

--4--
SELECT EMPLE.APELLIDO, EMPLE.OFICIO, DEPART.LOC
FROM EMPLE, DEPART
WHERE EMPLE.DEPT_NO=DEPART.DEPT_NO
AND UPPER(EMPLE.OFICIO)='ANALISTA';

--5--
SELECT E.EMP_NO, E.APELLIDO, NVL(TO_CHAR(J.EMP_NO),'SIN')"CODIGO JEFE", NVL(J.APELLIDO, 'NO TIENE JEFE')"APELLIDO JEFE"
FROM EMPLE E, EMPLE J
WHERE J.EMP_NO(+)=E.ID_JEFE
ORDER BY E.APELLIDO;

--6--

