--1--
SELECT *
FROM EMPLE
WHERE SALARIO > (SELECT AVG(SALARIO) FROM EMPLE);

--2--
SELECT D.DNOMBRE, E.SALARIO, D.DEPT_NO
FROM EMPLE E, DEPART d
WHERE E.DEPT_NO = D.DEPT_NO
AND D.DEPT_NO IN (SELECT D.DEPT_NO FROM DEPART D WHERE E.SALARIO > (SELECT AVG(E.SALARIO) FROM EMPLE E));

--3--
SELECT D.LOC "Localidad"
FROM DEPART D, EMPLE E
WHERE D.DEPT_NO = E.DEPT_NO
AND E.COMISION_PCT >= 10;

--3 SEGUNDA OPCION--


--4--









--5--
SELECT DEPART.DEPT_NO
FROM EMPLE, DEPART
WHERE EMPLE.DEPT_NO = DEPART.DEPT_NO
AND NOT EXISTS (SELECT DISTINCT EMP_NO FROM EMPLE);







--6--
SELECT *
FROM EMPLE
WHERE 2 <= (SELECT COUNT(*) FROM HJOB WHERE EMP_NO = EMPLE.EMP_NO);