--1--
CREATE OR REPLACE VIEW EMP_30 AS (
  SELECT EMP_NO, APELLIDO, SALARIO, DEPT_NO
  FROM EMPLE
  WHERE DEPT_NO = 30
);
--COMPROBACIONES
SELECT * FROM USER_VIEWS 
WHERE UPPER(VIEW_NAME) = 'EMP_30';
DESC EMP_30;

--2--
INSERT INTO EMPLE VALUES(9999,'URRUTIA','ANALISTA',7698,NULL,200000,NULL,30);
SELECT * FROM EMPLE;
SELECT * FROM EMP_30; --Mirar la vista

--3--
INSERT INTO EMP_30 VALUES(8888,'RUIZ',280000,30); 

INSERT INTO EMP_30 VALUES(7878,'RUIZ',280000,10); 


SELECT * FROM EMPLE
WHERE EMP_NO = 8888;

SELECT * FROM EMP_30
WHERE EMP_NO = 8888;

SELECT * FROM EMPLE
WHERE EMP_NO = 7878;

SELECT * FROM EMP_30
WHERE EMP_NO = 7878;


--4--
CREATE OR REPLACE VIEW EMP_30 AS (
  SELECT EMP_NO, APELLIDO, SALARIO, DEPT_NO
  FROM EMPLE
  WHERE DEPT_NO = 30)
  WITH CHECK OPTION CONSTRAINT EMP_30_ERROR;

INSERT INTO EMP_30 VALUES (1111, 'LOPEZ', 1200,30);  
INSERT INTO EMP_30 VALUES (2222, 'RUIZ', 2200,20);

SELECT * FROM EMP_30 WHERE EMP_NO IN (1111,2222);

SELECT * FROM EMPLE WHERE EMP_NO IN (1111,2222);

UPDATE EMP_30 
SET DEPT_NO = 10
WHERE EMP_NO = 7698;

--5--
CREATE OR REPLACE VIEW SAL_20 AS (
  SELECT EMP_NO, APELLIDO APE_EMP, SALARIO * 12 SAL_ANUAL
  FROM EMPLE
  WHERE DEPT_NO = 20
);

CREATE OR REPLACE VIEW SAL_20 (ID_EMP, APE_EMP, SAL_ANUAL) AS (
  SELECT EMP_NO, APELLIDO APE_EMP, SALARIO * 12 SAL_ANUAL
  FROM EMPLE
  WHERE DEPT_NO = 20
);

SELECT * FROM SAL_20;
SELECT * FROM EMPLE;

--6--
CREATE OR REPLACE VIEW DEPT_SUM (DEPT_NOMBRE, SAL_MIN, SAL_MAX, SAL_MED) AS
(SELECT D.DNOMBRE, MIN(E.SALARIO), MAX(E.SALARIO), AVG(E.SALARIO)
FROM DEPART D, EMPLE E
WHERE D.DEPT_NO = E.DEPT_NO
GROUP BY E.DEPT_NO, D.DNOMBRE);
--COMPROBAMOS
SELECT * FROM USER_VIEWS WHERE UPPER(VIEW_NAME) = 'DEPT_SUM';
DESC DEPT_SUM;
SELECT * FROM DEPT_SUM;

--7--
DROP VIEW SAL_20;

--8--
CREATE OR REPLACE VIEW V_DEPT_SALMAX AS
(SELECT DEPT_NO, MAX(SALARIO) SALARIO
FROM EMPLE
GROUP BY DEPT_NO);
--COMPROBAMOS
SELECT * FROM USER_VIEWS WHERE UPPER(VIEW_NAME) = 'V_DEPT_SALMAX';
DESC V_DEPT_SALMAX;
SELECT * FROM V_DEPT_SALMAX;