SET SERVEROUTPUT ON;

--1--
CREATE OR REPLACE PACKAGE GEST_DEPART2 IS
    PROCEDURE INSERTAR_DEPART (P_NOM VARCHAR2, P_LOC VARCHAR2);
    PROCEDURE BORRAR_DEPART (P_NUM NUMBER, P_NEWDEP NUMBER);
    PROCEDURE CAMBIAR_LOCALIDAD (P_NUM_DEP NUMBER, P_LOC VARCHAR2);
    PROCEDURE VISUALIZAR_LISTA_DEPART (C_DEPART OUT TCURSOR);
    PROCEDURE VISUALIZAR_DATOS_DEPART (P_NUM_DEP IN OUT NUMBER, P_NOM_DEP OUT VARCHAR2, P_LOC_DEP OUT VARCHAR2);
END;

CREATE OR REPLACE PACKAGE BODY GEST_DEPART2 IS 
    PROCEDURE INSERTAR_DEPART (P_NOM VARCHAR2, P_LOC VARCHAR2) AS
          V_ULTIMO_DEP DEPART.DEPT_NO%TYPE;
          E_NOMBRE_REPETIDO EXCEPTION;
          V_NOM_DEP DEPART.DNOMBRE%TYPE;
          V_COD SQLERRM%TYPE;
        BEGIN
          SELECT DNOMBRE INTO V_NOM_DEP 
          FROM DEPART
          WHERE UPPER(DNOMBRE) = UPPER(P_NOM_DEP);
          SELECT DNOMBRE INTO V_NOM_DEP 
          FROM DEPART
          WHERE UPPER(DNOMBRE) = UPPER(P_NOM_DEP);
          RAISE E_NOMBRE_REPETIDO;
        EXCEPTION
          WHEN NO_DATA_FOUND THEN
            SELECT MAX(DEPT_NO) INTO V_ULTIMO_DEP FROM DEPART;
            --IF V_ULTIMO_DEP IS NULL THEN 
            --END IF;
          --WHEN E_NOMBRE_REPETIDO THEN
            
          WHEN OTHERS THEN
            V_COD:=SQLCODE;
            V_MSG:=SQLERRM;
            V_SALIDA:='ERROR: '||TO_CHAR(V_COD)||'-'||V_MSG;
            RAISE_APLICATION_ERROR('-20999',V_SALIDA);
        COMMIT;
        END;
        
        --2--
        PROCEDURE BORRAR_DEPART (P_NUM NUMBER, P_NEWDEP NUMBER) AS   
          VDEPTNO DEPART.DEPT_NO%TYPE;
        BEGIN
          SELECT DEPT_NO INTO VDEPTNO
          FROM DEPART
          WHERE DEPT_NO=P_NUM;
          SELECT DEPT_NO INTO VDEPTNO
          FROM DEPART
          WHERE DEPT_NO=P_NEWDEP;
          UPDATE EMPLE SET DEPT_NO=P_NEWDEP
          WHERE DEPT_NO=P_NUM;
          DELETE FROM DEPART 
          WHERE DEPT_NO=P_NUM;
          IF SQL%FOUND THEN
            COMMIT;
          ELSE
            ROLLBACK;
          END IF;
        EXCEPTION
          WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO SE HAN ENCONTRADO EMPLEADOS EN '||TO_CHAR(P_NUM));
          WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR('-20999','ERROR DESCONOCIDO');
        END;
        
        --3--
        PROCEDURE CAMBIAR_LOCALIDAD (P_NUM_DEP NUMBER, P_LOC VARCHAR2) AS
          VDEPTNO DEPART.DEPT_NO%TYPE;
        BEGIN
          SELECT DEPT_NO INTO VDEPTNO
          FROM DEPART
          WHERE DEPT_NO=P_NUM_DEP;
          UPDATE DEPART SET LOC=P_LOC
          WHERE DEPT_NO=P_NUM_DEP;
        EXCEPTION
          WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('NO SE HAN ENCONTRADO DEPARTAMENTOS');
          WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR('-20999','ERROR DESCONOCIDO');
        END;
            
        --4--
        PROCEDURE VISUALIZAR_LISTA_DEPART (C_DEPART OUT TCURSOR) AS
        BEGIN
          OPEN C_DEPART FOR
            SELECT DEPT_NO, DNOMBRE, LOC
            FROM DEPART;
        END;
        
        --5--
        PROCEDURE VISUALIZAR_DATOS_DEPART (P_NUM_DEP IN OUT NUMBER, P_NOM_DEP OUT VARCHAR2, P_LOC_DEP OUT VARCHAR2) AS
        --BEGIN
        END;
END;

EXECUTE GEST_DEPART2.BORRAR_DEPART(10,20);

EXECUTE VISUALIZAR_LISTA_DEPART();

SELECT * FROM DEPART;